---
- hosts: all
  become: true
  tasks:
  - name: mysql install
    apt:
      deb: https://dev.mysql.com/get/mysql-apt-config_0.8.8-1_all.deb
    apt:
      name: ['mysql-server', 'mysql-client']
      update_cache: yes
  - name: mysql service
    service:
      name: mysql
      enabled: yes
      state: started
  - name: mysql database
    shell: mysql -u root -e 'CREATE DATABASE IF NOT EXISTS postcard;'
  - name: mysql user postcard user
    shell: mysql -u root -e "CREATE USER IF NOT EXISTS 'postcard-api'@'%' IDENTIFIED BY 'password';"
  - name: mysql user postcard user permissions
    shell: mysql -u root -e "GRANT ALL ON postcard.* TO 'postcard-api'@'%';"
